baseURL = 'https://shiomizaka.github.io/blog/'
languageCode = 'en-us'
title = 'A Study in Mystery'
theme = 'PaperMod'


[params]
  # --- ここから追記 ---
  # プロフィールモードを有効にする
  profileMode.enabled = true

  # トップページに表示するセクションを指定
  mainSections = ["posts"]

  # アイコンの上に表示される名前（サイトのtitleと同じでよければ不要）
  profileMode.title = "shiomizaka" # あなたの名前に変更

  # プロフィール下のサブタイトル
  profileMode.subtitle = "a study in mystery"

  # アイコン画像のパス（assetsフォルダからのパス）
  profileMode.imageUrl = "icon.jpg" # あなたの画像ファイル名に変更

  # 画像の幅と高さ（任意）
  profileMode.imageWidth = 120
  profileMode.imageHeight = 120

  # アイコン下に表示するボタン（任意）
# --- ここからがボタンの設定 ---
  [[params.profileMode.buttons]]
    name = "blog" # ボタンに表示されるテキスト
    url = "/blog//posts"   # リンク先のURL

  [[params.profileMode.buttons]]
    name = "categories"
    url = "/blog/categories"

  [[params.profileMode.buttons]]
    name = "tags"
    url = "/blog/tags"


  # --- ここまで --
[[params.socialIcons]]
  name = "bluesky"
  url = "https://bsky.app/profile/shiomizaka.bsky.social" # あなたのプロフィールURLに変更

 [[params.socialIcons]]
    name = "email"
    url = "mailto:shiomizaka@gmail.com"
  # --- ここまで ---

# Substackのアイコン
[[params.socialIcons]]
  name = "substack"
  url = "https://3kpoetryreading.substack.com" # あなたのSubstackのURLに変更

# Podcastのアイコン
[[params.socialIcons]]
  name = "podcast"
  url = "https://podcasts.apple.com/us/podcast/3k-podcast-3%E4%BA%BA%E3%81%AEk%E3%81%AB%E3%82%88%E3%82%8B%E8%A9%A9%E3%81%AE%E6%9C%97%E8%AA%AD%E4%BC%9A%E3%81%AE%E3%83%9D%E3%83%83%E3%83%89%E3%82%AD%E3%83%A3%E3%82%B9%E3%83%88/id1786861716?itscg=30200&itsct=podcast_box&ls=1&mttnsubad=1786861716" # あなたのPodcastのURLに変更

newContentEditor = "yaml"